--@@ROWCOUNT da o retorno de quantos registros foram afetados na última manutenção de dados
--O with eh igual ao Oracle
-- O NVL(<param1>, <param2>) do Oracle é o ISNULL(<param1>, <param2>) no SQL Server
-- O COALESCE(<param1>, <param2>, ..., <param_N>)